### ISSUE TITLE
Problem about parameter 'Url_Of_Project'

### ISSUE THREAD

**Issue by 392752120** [ElasticThree/ast-generator#7]
Hi,i have problems when i run this project.Can you help me.The console says:

2016-11-27 16:38:33 INFO  Neo4JDriver:882 - Insertion Query: CREATE (r:Repo {repoURL:'C:\Users\Hao\Desktop\programs\ast-generator-master\ast-generator-master',linesOfJavaCode:2826});
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.driver.v1.exceptions.ClientException: Invalid input 's': expected four hexadecimal digits specifying a unicode character (line 1, column 30 (offset: 29))
"CREATE (f:File {repoURL:'C:\Users\Hao\Desktop\programs\ast-generator-master\ast-generator-master'

**Comment by nbompetsis** [comment]
Hi!
From my experience, it seems that your input url has special characters and these cause issue in neo4j client.

Elastic-Team would appreciate it if you give us more feedback about your issue to modify our project  😃

**Comment by 392752120** [comment]
Thanks for your answer and suggestion.
My problem is that when the project get the variant 'name' in class FileNodeAST,it seems like "D:\project\**.java",but "\" has special means in java.
So after i modify the variant 'name' ,the problem has been solved.
By the way,your project is awosome,it helps me a lot.Thank you!

**Comment by nbompetsis** [comment]
Thanks for your reply.

I ran project and saw that the name variant from class FileNodeAST, initialized with the class' name.
For example -> Name = Example.java

So i don't understand that name variant gets value like "C:\users\..\Example.java"
But in any case, if you want, you can fork our project, create branch with your solution and make a pull request. 

Thank you so much for supporting Elastic-Team projects and OpenSource community.
**Also you can support Elastic-Team with a Star ⭐️  !!**
